import { createStore } from './store.js';

const $ = s => document.querySelector(s);
const money = n => new Intl.NumberFormat('es-PE', { style:'currency', currency:'PEN' }).format(Number(n || 0));
const esc = v => String(v ?? '').replace(/[&<>'\"]/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '\"':'&quot;' }[c]));
const labels = { new:'NUEVO', preparing:'PREPARANDO', ready:'LISTO', delivered:'ENTREGADO', cancelled:'CANCELADO' };
const nextStatus = { new:'preparing', preparing:'ready', ready:'delivered' };
const actionLabel = { preparing:'Preparar', ready:'Marcar listo', delivered:'Entregar' };
let store, session=null, role=null, cart=[], orders=[], products=[], categories=[], payments=[];
let currentView=null, historyFilter='all', productCategory='all', starting=false, assigning=false;
let refreshRunning=null, refreshQueued=false, lastReceipt=null, toastTimer=null;
const isCashier=()=>['admin','manager','cashier'].includes(role);
const isKitchen=()=>['admin','manager','kitchen'].includes(role);
const cartTotal=()=>cart.reduce((s,x)=>s+Number(x.price||0)*Number(x.quantity||0),0);
const categoryCode=p=>p.categories?.code||p.category_id||p.category||'other';
const categoryName=p=>p.categories?.name||p.category||'Sin categoría';
const isToday=v=>new Date(v).toLocaleDateString('es-PE',{timeZone:'America/Lima'})===new Date().toLocaleDateString('es-PE',{timeZone:'America/Lima'});
function toast(message){const t=$('#toast');if(!t)return;t.textContent=message;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),3200)}
async function withTimeout(promise,ms,message){let timer;const timeout=new Promise((_,reject)=>timer=setTimeout(()=>reject(new Error(message)),ms));try{return await Promise.race([promise,timeout])}finally{clearTimeout(timer)}}
function saveCart(){try{localStorage.setItem('coco_loco_cart',JSON.stringify(cart.map(x=>({id:x.id,name:x.name,price:x.price,description:x.description,quantity:x.quantity,category:x.category}))))}catch{}}
function restoreCart(){try{const a=JSON.parse(localStorage.getItem('coco_loco_cart')||'[]');if(Array.isArray(a))cart=a.filter(x=>x?.id&&Number(x.quantity)>0).map(x=>({...x,quantity:Number(x.quantity)}))}catch{cart=[]}}
function busy(b,on){if(!b)return;if(on){b.dataset.oldText=b.innerHTML;b.disabled=true;b.innerHTML='Guardando…'}else{b.disabled=false;if(b.dataset.oldText)b.innerHTML=b.dataset.oldText}}
function renderCatalog(){const search=$('#product-search');if(!search)return;const q=search.value.toLowerCase().trim();const tabs=[{code:'all',name:'Todos'},...categories];$('#category-tabs').innerHTML=tabs.map(c=>`<button class="category ${productCategory===c.code?'is-selected':''}" data-category="${esc(c.code)}" type="button">${esc(c.name)}</button>`).join('');const list=products.filter(p=>(productCategory==='all'||categoryCode(p)===productCategory)&&`${p.name} ${p.description||''} ${categoryName(p)}`.toLowerCase().includes(q));$('#product-list').innerHTML=list.length?list.map(p=>`<article class="product"><span class="product-icon">${categoryName(p)==='Bebidas'?'◉':'♨'}</span><div><strong>${esc(p.name)}</strong><small>${esc(p.description||categoryName(p))}</small></div><button class="add-product" data-id="${esc(p.id)}" type="button"><span>${money(p.price)}</span><b>+</b></button></article>`).join(''):'<p class="empty">No encontramos productos.</p>'}
function renderPayments(){const s=$('#payment-method');if(!s)return;s.innerHTML=payments.map(p=>`<option value="${esc(p.code)}">${esc(p.name)}</option>`).join('');toggleCash()}
function renderChange(){const received=Number($('#cash-received')?.value||0),change=received-cartTotal();$('#change-amount').textContent=money(Math.max(change,0));$('#change-row')?.classList.toggle('negative',change<0)}
function renderCart(){const count=cart.reduce((s,x)=>s+Number(x.quantity||0),0);$('#cart-count').textContent=`${count} ${count===1?'producto':'productos'}`;$('#cart-total').textContent=money(cartTotal());$('#dialog-total').textContent=money(cartTotal());$('#open-cart').disabled=!cart.length;$('#cart-items').innerHTML=cart.length?cart.map(x=>`<div class="cart-line"><div><strong>${esc(x.name)}</strong><small>${esc(x.description||categoryName(x))}</small></div><div class="quantity"><button data-action="less" data-id="${esc(x.id)}" type="button">−</button><b>${x.quantity}</b><button data-action="more" data-id="${esc(x.id)}" type="button">+</button></div><strong>${money(Number(x.price)*x.quantity)}</strong></div>`).join(''):'<p class="empty">Tu pedido está vacío.</p>';renderChange();saveCart()}
function addProduct(id){const p=products.find(x=>String(x.id)===String(id));if(!p)return toast('No se encontró ese producto.');const line=cart.find(x=>String(x.id)===String(id));if(line)line.quantity++;else cart.push({...p,quantity:1});renderCart()}
function orderCard(o,kitchenMode=false){const lines=o.order_items||[],target=nextStatus[o.status],time=new Date(o.created_at).toLocaleTimeString('es-PE',{hour:'2-digit',minute:'2-digit'});const action=kitchenMode&&target?`<button class="status-button" data-order="${esc(o.id)}" data-next="${esc(target)}" type="button">${actionLabel[target]}</button>`:`<span>${esc(payments.find(p=>p.code===o.payment_type)?.name||o.payment_type||'')}</span>`;return `<article class="order-card"><div class="order-card__head"><div><span class="order-number">#${String(o.order_number).padStart(3,'0')}</span><small>${time}</small></div><span class="status status--${esc(o.status)}">${esc(labels[o.status]||o.status)}</span></div><p class="order-lines">${lines.map(x=>`${Number(x.quantity)}× ${esc(x.product_name)}`).join('<br>')}</p>${o.notes?`<p class="note">${esc(o.notes)}</p>`:''}<div class="order-card__foot"><strong>${money(o.total)}</strong>${action}</div></article>`}
function renderKitchen(){const active=orders.filter(o=>!['delivered','cancelled'].includes(o.status));$('#kitchen-summary').innerHTML=['new','preparing','ready'].map(s=>`<span><b>${active.filter(o=>o.status===s).length}</b>${labels[s]}</span>`).join('');$('#kitchen-list').innerHTML=active.length?active.map(o=>orderCard(o,true)).join(''):'<p class="empty">No hay pedidos pendientes.</p>'}
function renderHistory(){const visible=orders.filter(o=>historyFilter==='all'?true:historyFilter==='pending'?!['delivered','cancelled'].includes(o.status):o.status===historyFilter);$('#history-list').innerHTML=visible.length?visible.map(o=>orderCard(o)).join(''):'<p class="empty">No hay pedidos para mostrar.</p>';document.querySelectorAll('#history-filter .filter').forEach(b=>b.classList.toggle('is-selected',b.dataset.status===historyFilter))}
function renderSales(){const daily=orders.filter(o=>isToday(o.created_at)),done=daily.filter(o=>o.status==='delivered');$('#sales-total').textContent=money(done.reduce((s,o)=>s+Number(o.total||0),0));$('#sales-count').textContent=`${daily.length} pedidos registrados`;$('#sales-cards').innerHTML=payments.map(p=>`<div><span>${esc(p.name)}</span><b>${money(done.filter(o=>o.payment_type===p.code).reduce((s,o)=>s+Number(o.total||0),0))}</b></div>`).join('');const counts={};done.forEach(o=>(o.order_items||[]).forEach(x=>{counts[x.product_name]=(counts[x.product_name]||0)+Number(x.quantity||0)}));$('#top-products').innerHTML=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,5).map(([n,q])=>`<p><span>${esc(n)}</span><b>${q}</b></p>`).join('')||'<p class="empty">Aún no hay ventas entregadas.</p>'}
async function refresh(){if(!store||!session?.user?.id)return;if(refreshRunning){refreshQueued=true;return refreshRunning}refreshRunning=(async()=>{try{orders=await withTimeout(store.listOrders(),10000,'La consulta de pedidos tardó demasiado.');renderKitchen();renderHistory();renderSales()}catch(e){console.error(e);toast(`No se pudieron cargar pedidos: ${e.message}`)}finally{refreshRunning=null;if(refreshQueued){refreshQueued=false;queueMicrotask(refresh)}}})();return refreshRunning}
function toggleCash(){const p=$('#payment-method')?.value,show=p==='cash'||p==='EFECTIVO';if($('#cash-field'))$('#cash-field').hidden=!show;if($('#change-row'))$('#change-row').hidden=!show;if(!show&&$('#cash-received'))$('#cash-received').value='';renderChange()}
function showReceipt(saved,payment,received,items,notes){const d=$('#receipt-dialog');if(!d)return;const paymentName=payments.find(p=>p.code===payment)?.name||payment;lastReceipt={orderNumber:saved.order_number,total:Number(saved.total),paymentName,received:Number(received||0),change:Math.max(Number(received||0)-Number(saved.total),0),items:items.map(x=>({name:x.name,quantity:x.quantity,price:Number(x.price)})),notes:notes||''};$('#receipt-number').textContent=`PEDIDO #${String(saved.order_number).padStart(3,'0')} · ${new Date().toLocaleTimeString('es-PE',{hour:'2-digit',minute:'2-digit'})}`;$('#receipt-lines').innerHTML=items.map(x=>`<div class="receipt-line"><span>${x.quantity}× ${esc(x.name)}</span><strong>${money(Number(x.price)*x.quantity)}</strong></div>`).join('');$('#receipt-total').textContent=money(saved.total);$('#receipt-payment').textContent=paymentName;const cash=payment==='cash';$('#receipt-received-row').hidden=!cash;$('#receipt-change-row').hidden=!cash;if(cash){$('#receipt-received').textContent=money(received);$('#receipt-change').textContent=money(Math.max(Number(received)-Number(saved.total),0))}$('#receipt-note').textContent=notes?`Nota: ${notes}`:'';$('#receipt-note').hidden=!notes;if(!d.open)d.showModal()}
function shareWhatsApp(){if(!lastReceipt)return;const lines=lastReceipt.items.map(x=>`• ${x.quantity}× ${x.name} — ${money(x.price*x.quantity)}`).join('\n');const cash=lastReceipt.paymentName.toLowerCase().includes('efectivo')?`\nRecibido: ${money(lastReceipt.received)}\nVuelto: ${money(lastReceipt.change)}`:'';const text=`*ANTICUCHERÍA COCO LOCO*\n🧾 Pedido #${String(lastReceipt.orderNumber).padStart(3,'0')}\n\n${lines}\n\n*Total: ${money(lastReceipt.total)}*\nPago: ${lastReceipt.paymentName}${cash}${lastReceipt.notes?`\nNota: ${lastReceipt.notes}`:''}\n\n¡Gracias por tu pedido! ❤️`;const a=document.createElement('a');a.href=`https://wa.me/?text=${encodeURIComponent(text)}`;a.target='_blank';a.rel='noopener noreferrer';a.click()}
async function placeOrder(e){e.preventDefault();if(!session?.user?.id)return toast('La sesión no está activa.');const items=cart.map(x=>({...x})),payment=$('#payment-method')?.value||'cash',received=Number($('#cash-received')?.value||0),notes=$('#order-note')?.value.trim()||'',total=cartTotal();if(!items.length)return toast('Agrega al menos un producto.');if(total<=0)return toast('El total del pedido no es válido.');if(payment==='cash'&&received<total)return toast(`Faltan ${money(total-received)} para completar el pago.`);const b=$('#place-order');busy(b,true);try{const saved=await withTimeout(store.createOrder({items,paymentMethodCode:payment,notes,cashReceived:received}),15000,'No hubo respuesta de Supabase al registrar el pedido.');if(!saved?.id)throw new Error('Supabase no devolvió el pedido registrado.');cart=[];saveCart();$('#cash-received').value='';$('#order-note').value='';if($('#cart-dialog').open)$('#cart-dialog').close();renderCart();await refresh();showReceipt(saved,payment,received,items,notes);toast(`Pedido #${String(saved.order_number).padStart(3,'0')} registrado correctamente.`)}catch(err){console.error('createOrder',err);toast(`No se pudo registrar el pedido: ${err.message||'Error desconocido'}`)}finally{busy(b,false)}}
function changeView(id,push=true){const target=document.getElementById(id);if(!target||target.hidden)return;document.querySelectorAll('.view').forEach(v=>v.classList.toggle('is-active',v.id===id));document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('is-active',n.dataset.view===id));currentView=id;window.scrollTo(0,0);if(push&&history.state?.cocoView!==id)history.pushState({cocoView:id},'',`#${id}`)}
function applyRole(){document.querySelectorAll('[data-requires="cashier"]').forEach(x=>x.hidden=!isCashier());document.querySelectorAll('[data-requires="kitchen"]').forEach(x=>x.hidden=!isKitchen());changeView(isCashier()?'order-view':isKitchen()?'kitchen-view':'order-view',false)}
async function start(snap,override=null){if(starting)return;if(!snap?.user?.id)throw new Error('No hay una sesión válida.');starting=true;try{const id=override||await withTimeout(store.getIdentity(),10000,'No se pudo comprobar el área del dispositivo.');role=id?.role||null;if(id?.user_id!==snap.user.id||id?.active!==true||!['admin','manager','cashier','kitchen'].includes(role))throw new Error('Este dispositivo todavía no tiene un área asignada.');session=snap;$('#auth-view').hidden=true;$('#app-shell').hidden=false;$('#user-name').textContent=id.display_name||(role==='cashier'?'Caja':'Cocina');$('#user-role').textContent=String(role).toUpperCase();applyRole();const catalog=await withTimeout(store.loadCatalog(),10000,'El catálogo tardó demasiado en cargar.');products=catalog.products||[];categories=catalog.categories||[];payments=catalog.payments||[];renderCatalog();renderPayments();restoreCart();renderCart();await refresh();await withTimeout(store.subscribeToOrders(),10000,'No se pudo activar la sincronización en tiempo real.');$('#sync-status span').textContent='En tiempo real'}finally{starting=false}}
async function enterArea(selectedRole){if(assigning)return;assigning=true;$('#auth-error').textContent='';document.querySelectorAll('.role-button').forEach(b=>b.disabled=true);try{const r=await withTimeout(store.signInAnonymously(),15000,'Supabase no respondió al iniciar la sesión.');if(!r?.session?.user?.id)throw new Error('Supabase no devolvió una sesión válida.');session=r.session;const id=await withTimeout(store.claimDeviceRole(selectedRole,selectedRole==='cashier'?'Caja':'Cocina'),10000,'No se pudo asignar el área.');await start(r.session,id);localStorage.setItem('coco_loco_area',selectedRole)}catch(e){console.error(e);$('#auth-error').textContent=e.message||'No se pudo ingresar.';session=null;role=null}finally{assigning=false;document.querySelectorAll('.role-button').forEach(b=>b.disabled=false)}}
async function handleSession(value){if(assigning)return;if(!value?.user?.id){session=null;role=null;orders=[];await store?.unsubscribe();$('#app-shell').hidden=true;$('#auth-view').hidden=false;return}session=value;try{await start(value)}catch(e){console.error(e);role=null;await store.unsubscribe();$('#app-shell').hidden=true;$('#auth-view').hidden=false;$('#auth-error').textContent=e.message||'No se pudo iniciar la aplicación.'}}
$('#enter-cashier').onclick=()=>enterArea('cashier');$('#enter-kitchen').onclick=()=>enterArea('kitchen');$('#sign-out').onclick=async()=>{try{localStorage.removeItem('coco_loco_area');await store.signOut()}catch(e){toast(e.message)}};
$('#category-tabs').onclick=e=>{const b=e.target.closest('[data-category]');if(b){productCategory=b.dataset.category;renderCatalog()}};$('#product-search').oninput=renderCatalog;$('#product-search').onkeydown=e=>{if(e.key==='Escape'){e.target.value='';renderCatalog()}};$('#product-list').onclick=e=>{const b=e.target.closest('.add-product');if(b)addProduct(b.dataset.id)};
$('#open-cart').onclick=()=>{if(cart.length)$('#cart-dialog').showModal()};$('#cart-items').onclick=e=>{const b=e.target.closest('button[data-id]');if(!b)return;const line=cart.find(x=>String(x.id)===String(b.dataset.id));if(!line)return;if(b.dataset.action==='more')line.quantity++;if(b.dataset.action==='less'){line.quantity--;if(line.quantity<=0)cart=cart.filter(x=>x!==line)}renderCart()};$('#payment-method').onchange=toggleCash;$('#cash-received').oninput=renderChange;$('#cart-form').onsubmit=placeOrder;
$('#new-order').onclick=()=>{cart=[];renderCart();$('#product-search').focus();toast('Pedido actual vaciado.')};$('#refresh-kitchen').onclick=refresh;$('#close-cash').onclick=refresh;
$('#kitchen-list').onclick=async e=>{const b=e.target.closest('[data-order]');if(!b)return;b.disabled=true;try{await withTimeout(store.updateOrderStatus(b.dataset.order,b.dataset.next),10000,'La actualización tardó demasiado.');await refresh()}catch(err){toast(`No se pudo actualizar: ${err.message}`)}finally{b.disabled=false}};
$('#history-filter').onclick=e=>{const b=e.target.closest('.filter');if(b?.dataset.status){historyFilter=b.dataset.status;renderHistory()}};$('#close-receipt').onclick=()=>$('#receipt-dialog')?.close();$('#whatsapp-receipt').onclick=shareWhatsApp;document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>changeView(b.dataset.view));
window.addEventListener('popstate',()=>{if($('#receipt-dialog')?.open){$('#receipt-dialog').close();return}if($('#cart-dialog')?.open){$('#cart-dialog').close();return}const id=location.hash.slice(1);if(id&&document.getElementById(id))changeView(id,false)});window.addEventListener('hashchange',()=>{const id=location.hash.slice(1);if(id&&document.getElementById(id)&&id!==currentView)changeView(id,false)});
(async()=>{try{store=await createStore({onOrdersChange:()=>refresh(),onAuthChange:handleSession});const r=await withTimeout(store.getSession(),10000,'Supabase no respondió al comprobar la sesión.');await handleSession(r?.session||null);const initial=location.hash.slice(1);if(initial&&document.getElementById(initial)&&!document.getElementById(initial).hidden)changeView(initial,false)}catch(e){console.error(e);$('#auth-error').textContent=e.message||'No se pudo iniciar la aplicación.'}})();
