import { createStore } from './store.js';

const $ = s => document.querySelector(s);
const money = n => new Intl.NumberFormat('es-PE', { style: 'currency', currency: 'PEN' }).format(Number(n || 0));
const esc = v => String(v ?? '').replace(/[&<>'"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[c]));
const priority = ['admin', 'manager', 'cashier', 'kitchen'];
const labels = { new: 'NUEVO', preparing: 'PREPARANDO', ready: 'LISTO', delivered: 'ENTREGADO', cancelled: 'CANCELADO' };
const next = { new: 'preparing', preparing: 'ready', ready: 'delivered' };
const actions = { preparing: 'Preparar', ready: 'Marcar listo', delivered: 'Entregar' };
let store, cart = [], orders = [], products = [], categories = [], payments = [], role, session, category = 'all', history = 'all';
const total = () => cart.reduce((sum, x) => sum + Number(x.price) * x.quantity, 0);
const today = d => new Date(d).toDateString() === new Date().toDateString();
const cashier = () => ['admin', 'manager', 'cashier'].includes(role);
const kitchen = () => ['admin', 'manager', 'kitchen'].includes(role);
function toast(message) { const t = $('#toast'); t.textContent = message; t.classList.add('show'); setTimeout(() => t.classList.remove('show'), 3000); }
const categoryCode = p => p.categories?.code || p.category_id || p.category || 'other';
const categoryName = p => p.categories?.name || p.category || 'Sin categoría';
function renderCatalog() {
  const q = $('#product-search').value.toLowerCase().trim();
  $('#category-tabs').innerHTML = [{ code: 'all', name: 'Todos' }, ...categories].map(c => `<button class="category ${category === c.code ? 'is-selected' : ''}" data-category="${esc(c.code)}">${esc(c.name)}</button>`).join('');
  const list = products.filter(p => (category === 'all' || categoryCode(p) === category) && `${p.name} ${p.description || ''} ${categoryName(p)}`.toLowerCase().includes(q));
  $('#product-list').innerHTML = list.length ? list.map(p => `<article class="product"><span class="product-icon">${categoryName(p) === 'Bebidas' ? '◉' : '♨'}</span><div><strong>${esc(p.name)}</strong><small>${esc(p.description || categoryName(p))}</small></div><button class="add-product" data-id="${p.id}"><span>${money(p.price)}</span><b>+</b></button></article>`).join('') : '<p class="empty">No encontramos productos.</p>';
}
function renderPayments() { $('#payment-method').innerHTML = payments.map(p => `<option value="${esc(p.code)}">${esc(p.name)}</option>`).join(''); toggleCash(); }
function renderChange() { const change = Number($('#cash-received').value || 0) - total(); $('#change-amount').textContent = money(Math.max(change, 0)); $('#change-row').classList.toggle('negative', change < 0); }
function renderCart() {
  const count = cart.reduce((sum, x) => sum + x.quantity, 0); $('#cart-count').textContent = `${count} ${count === 1 ? 'producto' : 'productos'}`; $('#cart-total').textContent = money(total()); $('#dialog-total').textContent = money(total()); $('#open-cart').disabled = !cart.length;
  $('#cart-items').innerHTML = cart.length ? cart.map(x => `<div class="cart-line"><div><strong>${esc(x.name)}</strong><small>${esc(x.description || categoryName(x))}</small></div><div class="quantity"><button data-action="less" data-id="${x.id}">−</button><b>${x.quantity}</b><button data-action="more" data-id="${x.id}">+</button></div><strong>${money(Number(x.price) * x.quantity)}</strong></div>`).join('') : '<p class="empty">Tu pedido está vacío.</p>'; renderChange();
}
function add(id) { const p = products.find(x => x.id === id), line = cart.find(x => x.id === id); if (!p) return; line ? line.quantity++ : cart.push({ ...p, quantity: 1 }); renderCart(); }
function card(o, forKitchen = false) {
  const status = labels[o.status] || o.status, lines = o.order_items || [], time = new Date(o.created_at).toLocaleTimeString('es-PE', { hour: '2-digit', minute: '2-digit' }), target = next[o.status];
  return `<article class="order-card"><div class="order-card__head"><div><span class="order-number">#${String(o.order_number).padStart(3, '0')}</span><small>${time}</small></div><span class="status status--${esc(o.status)}">${esc(status)}</span></div><p class="order-lines">${lines.map(x => `${x.quantity}× ${esc(x.product_name)}`).join('<br>')}</p>${o.notes ? `<p class="note">${esc(o.notes)}</p>` : ''}<div class="order-card__foot"><strong>${money(o.total)}</strong>${forKitchen && target ? `<button class="status-button" data-order="${o.id}" data-next="${target}">${actions[target]}</button>` : `<span>${esc(payments.find(x => x.code === o.payment_type)?.name || o.payment_type)}</span>`}</div></article>`;
}
function renderKitchen() { const active = orders.filter(o => !['delivered', 'cancelled'].includes(o.status)); $('#kitchen-summary').innerHTML = ['new', 'preparing', 'ready'].map(s => `<span><b>${active.filter(o => o.status === s).length}</b>${labels[s]}</span>`).join(''); $('#kitchen-list').innerHTML = active.length ? active.map(o => card(o, true)).join('') : '<p class="empty">No hay pedidos pendientes.</p>'; }
function renderHistory() { const visible = orders.filter(o => history === 'all' || (history === 'pending' ? !['delivered', 'cancelled'].includes(o.status) : o.status === history)); $('#history-list').innerHTML = visible.length ? visible.map(o => card(o)).join('') : '<p class="empty">No hay pedidos para mostrar.</p>'; }
function renderSales() { const daily = orders.filter(o => today(o.created_at)), done = daily.filter(o => o.status === 'delivered'); $('#sales-total').textContent = money(done.reduce((s, o) => s + Number(o.total), 0)); $('#sales-count').textContent = `${daily.length} pedidos registrados`; $('#sales-cards').innerHTML = payments.map(p => `<div><span>${esc(p.name)}</span><b>${money(done.filter(o => o.payment_type === p.code).reduce((s, o) => s + Number(o.total), 0))}</b></div>`).join(''); const counts = {}; done.forEach(o => (o.order_items || []).forEach(x => { counts[x.product_name] = (counts[x.product_name] || 0) + x.quantity; })); $('#top-products').innerHTML = Object.entries(counts).sort((a, b) => b[1] - a[1]).slice(0, 5).map(([n, q]) => `<p><span>${esc(n)}</span><b>${q}</b></p>`).join('') || '<p class="empty">Aún no hay ventas entregadas.</p>'; }
async function refresh() { if (!session) return; try { orders = await store.listOrders(); renderKitchen(); renderHistory(); renderSales(); } catch (error) { toast(`No se pudieron cargar pedidos: ${error.message}`); } }
function toggleCash() { const show = $('#payment-method').value === 'cash'; $('#cash-field').hidden = !show; $('#change-row').hidden = !show; }
async function place(event) {
  event.preventDefault(); const payment = $('#payment-method').value, received = Number($('#cash-received').value || 0); if (payment === 'cash' && received < total()) return toast(`Faltan ${money(total() - received)} para completar el pago.`);
  const button = $('#place-order'); button.disabled = true; try { const saved = await store.createOrder({ items: cart, paymentMethodCode: payment, notes: $('#order-note').value.trim(), cashReceived: received }); cart = []; $('#cart-dialog').close(); $('#cash-received').value = ''; $('#order-note').value = ''; renderCart(); await refresh(); toast(`Pedido #${String(saved.order_number).padStart(3, '0')} registrado.`); } catch (error) { toast(`No se pudo registrar el pedido: ${error.message}`); } finally { button.disabled = false; }
}
function view(id) { document.querySelectorAll('.view').forEach(v => v.classList.toggle('is-active', v.id === id)); document.querySelectorAll('.nav-item').forEach(n => n.classList.toggle('is-active', n.dataset.view === id)); scrollTo(0, 0); }
function applyRole() { document.querySelectorAll('[data-requires="cashier"]').forEach(x => x.hidden = !cashier()); document.querySelectorAll('[data-requires="kitchen"]').forEach(x => x.hidden = !kitchen()); if (!cashier() && kitchen()) view('kitchen-view'); }
async function start() {
  const [roles, profile] = await Promise.all([store.getRoles(), store.getProfile(session.user.id)]); role = priority.find(r => roles.map(x => x.role).includes(r)); if (!profile.active || !role) throw new Error('Tu usuario no tiene un rol operativo. Pide al administrador asignarte CAJA o COCINA.');
  $('#auth-view').hidden = true; $('#app-shell').hidden = false; $('#user-name').textContent = profile.display_name || session.user.email; $('#user-role').textContent = role.toUpperCase(); applyRole(); const catalog = await store.loadCatalog(); products = catalog.products; categories = catalog.categories; payments = catalog.payments; renderCatalog(); renderPayments(); renderCart(); await refresh(); await store.subscribeToOrders();
}
async function handleSession(value) { session = value; if (!session) { role = undefined; await store?.unsubscribe(); $('#app-shell').hidden = true; $('#auth-view').hidden = false; return; } try { await start(); } catch (error) { await store.signOut(); $('#auth-error').textContent = error.message; } }
$('#login-form').onsubmit = async event => { event.preventDefault(); $('#auth-error').textContent = ''; const b = $('#login-submit'); b.disabled = true; try { await store.signIn($('#email').value.trim(), $('#password').value); } catch (error) { $('#auth-error').textContent = error.message || 'No se pudo iniciar sesión.'; } finally { b.disabled = false; } };
$('#sign-out').onclick = async () => { try { await store.signOut(); } catch (error) { toast(error.message); } }; $('#category-tabs').onclick = e => { if (e.target.dataset.category) { category = e.target.dataset.category; renderCatalog(); } }; $('#product-search').oninput = renderCatalog; $('#product-list').onclick = e => { const b = e.target.closest('.add-product'); if (b) add(b.dataset.id); }; $('#open-cart').onclick = () => $('#cart-dialog').showModal(); $('#cart-items').onclick = e => { const b = e.target.closest('button'); if (!b) return; const line = cart.find(x => x.id === b.dataset.id); if (!line) return; if (b.dataset.action === 'more') line.quantity++; else if (--line.quantity === 0) cart = cart.filter(x => x !== line); renderCart(); }; $('#payment-method').onchange = toggleCash; $('#cash-received').oninput = renderChange; $('#cart-form').onsubmit = place; $('#new-order').onclick = () => { if (cart.length && confirm('¿Vaciar el pedido actual?')) { cart = []; renderCart(); } }; $('#refresh-kitchen').onclick = refresh; $('#kitchen-list').onclick = async e => { const b = e.target.closest('[data-order]'); if (!b) return; b.disabled = true; try { await store.updateOrderStatus(b.dataset.order, b.dataset.next); await refresh(); } catch (error) { toast(`No se pudo actualizar: ${error.message}`); } finally { b.disabled = false; } }; $('#history-filter').onclick = e => { if (e.target.dataset.status) { history = e.target.dataset.status; document.querySelectorAll('.filter').forEach(x => x.classList.toggle('is-selected', x === e.target)); renderHistory(); } }; document.querySelectorAll('.nav-item').forEach(b => b.onclick = () => view(b.dataset.view));
try { store = await createStore({ onOrdersChange: refresh, onAuthChange: handleSession }); $('#sync-status span').textContent = store.mode; const { session: initial } = await store.getSession(); await handleSession(initial); } catch (error) { $('#auth-error').textContent = error.message; }
