export const CATEGORIES=['Todos','Para parrilla','Duos','Trío','Acompañantes','Bebidas','Dulces','Salsas'];
const p=(id,category,name,price,detail='')=>({id,category,name,price,detail});
export const PRODUCTS=[
p('anticucho-15','Para parrilla','Anticuchos',15,'Porción'),p('anticucho-20','Para parrilla','Anticuchos',20,'Porción grande'),p('mollejitas-10','Para parrilla','Mollejitas',10,'Porción'),p('mollejitas-15','Para parrilla','Mollejitas',15,'Porción grande'),p('rachi-15','Para parrilla','Rachi',15,'Porción'),p('rachi-20','Para parrilla','Rachi',20,'Porción grande'),p('pollada-15','Para parrilla','Pollada',15),p('parrillada-17','Para parrilla','Parrillada',17),p('alitas-15','Para parrilla','Alitas',15,'Porción'),p('alitas-28','Para parrilla','Alitas',28,'Porción grande'),
p('duo-rachi-molleja-22','Duos','Rachi + Mollejitas',22,'Porción'),p('duo-rachi-molleja-30','Duos','Rachi + Mollejitas',30,'Porción grande'),p('duo-molleja-anticucho-22','Duos','Mollejitas + Anticuchos',22,'Porción'),p('duo-molleja-anticucho-30','Duos','Mollejitas + Anticuchos',30,'Porción grande'),p('duo-rachi-anticucho-28','Duos','Rachi + Anticucho',28,'Porción'),p('duo-rachi-anticucho-35','Duos','Rachi + Anticucho',35,'Porción grande'),p('trio-40','Trío','Anticucho + Rachi + Mollejitas',40),
p('papa','Acompañantes','Papa',1.5),p('choclo','Acompañantes','Choclo',3),p('chaufa-5','Acompañantes','Arroz chaufa',5,'Porción'),p('chaufa-10','Acompañantes','Arroz chaufa',10,'Porción grande'),p('tallarines-5','Acompañantes','Tallarines rojos',5,'Porción'),p('tallarines-10','Acompañantes','Tallarines rojos',10,'Porción grande'),p('yuca','Acompañantes','Yuca',1.5),p('hotdog','Acompañantes','Hot dog',2.5),
p('inca-kola','Bebidas','Inca Kola',4.5),p('coca-cola','Bebidas','Coca Cola',4.5),p('kr','Bebidas','KR',1.5),p('guaranita','Bebidas','Guaranita',1.5),p('agua-sin-gas','Bebidas','Agua sin gas',1.5),p('agua-con-gas','Bebidas','Agua con gas',2),p('jamaica','Bebidas','Agua de Jamaica 10 oz',2),
p('mazamorra','Dulces','Mazamorra',4),p('combinado','Dulces','Combinado',4,'Arroz con leche + mazamorra'),p('arroz-leche','Dulces','Arroz con leche',4),p('arroz-zambito','Dulces','Arroz Zambito',4),p('keke','Dulces','Keke',2),p('torta-chocolate','Dulces','Torta de Chocolate',5),p('gelatina','Dulces','Gelatina de fresa',2),p('flan','Dulces','Flan',3),p('budin','Dulces','Budín',3),p('curichis','Dulces','Curichis',3),
p('rocoto','Salsas','Crema de rocoto',0),p('huacatay','Salsas','Ají de huacatay',0),p('chimichurri','Salsas','Chimichurri',0),p('cocona','Salsas','Ají de cocona',0),p('aji-casa','Salsas','Ají de casa',0)];
